//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerDLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolMonitorEntities4 : DbContext
    {
        public SchoolMonitorEntities4()
            : base("name=SchoolMonitorEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CheckLessons> CheckLessons { get; set; }
        public DbSet<Classroom> Classroom { get; set; }
        public DbSet<Lessons> Lessons { get; set; }
    }
}
